/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.jogoDaVelha;

import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * @author Hygor
 * @author Igor
 */
public class telaConfiguracao extends javax.swing.JFrame {

    int limite = 10;

    public telaConfiguracao() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("launcher.png")));
        txf_NomeJ1.setDocument(new soLetras());
        txf_NomeJ2.setDocument(new soLetras());
        dica.setToolTipText("<html><b>Dica:</b> Você pode ou não colocar nome de jogador! <html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XouO = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txf_NomeJ1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txf_NomeJ2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbx_rodadas = new javax.swing.JComboBox<>();
        btn_Voltar = new javax.swing.JButton();
        btn_OK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        radX = new javax.swing.JRadioButton();
        radO = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        dica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Jogo da Velha");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Configurar Jogo"));

        jLabel1.setText("Nome do jogador 1:");

        txf_NomeJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NomeJ1ActionPerformed(evt);
            }
        });
        txf_NomeJ1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_NomeJ1KeyTyped(evt);
            }
        });

        jLabel2.setText("Nome do jogador 2:");

        txf_NomeJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_NomeJ2ActionPerformed(evt);
            }
        });
        txf_NomeJ2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txf_NomeJ2KeyTyped(evt);
            }
        });

        jLabel4.setText("Quantidade de rodadas:");

        cbx_rodadas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Selecione a quantidade>", "1", "3", "5", "7", "9" }));

        btn_Voltar.setText("Voltar");
        btn_Voltar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_OK.setText("OK");
        btn_OK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OKActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/jogoDaVelha/Imagens/config.png"))); // NOI18N

        XouO.add(radX);
        radX.setText("X");

        XouO.add(radO);
        radO.setText("O");

        jLabel5.setText("Simbolo do jogador 1:");

        dica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/jogoDaVelha/Imagens/Yoda.png"))); // NOI18N
        dica.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_Voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radX)
                                            .addComponent(txf_NomeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radO)))
                                    .addComponent(jLabel5))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txf_NomeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbx_rodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(dica)
                        .addGap(22, 22, 22))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txf_NomeJ1, txf_NomeJ2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_OK, btn_Voltar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {radO, radX});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dica))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_NomeJ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_NomeJ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbx_rodadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Voltar)
                            .addComponent(btn_OK, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(radX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radO)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_OK, btn_Voltar});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {radO, radX});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txf_NomeJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NomeJ1ActionPerformed

    }//GEN-LAST:event_txf_NomeJ1ActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        jogoDaVelhaUI jpDaVelhaUI = new jogoDaVelhaUI();
        jpDaVelhaUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void btn_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OKActionPerformed
        if (cbx_rodadas.getSelectedItem().equals("<Selecione a quantidade>")) {
            JOptionPane.showMessageDialog(null, "Selecione quantas rodadas deseja!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        } else if (!txf_NomeJ1.getText().isEmpty() && !txf_NomeJ2.getText().isEmpty() && txf_NomeJ1.getText().equals(txf_NomeJ2.getText())) {

            JOptionPane.showMessageDialog(null, "Coloque nomes diferentes para cada jogador!", "Atenção!", JOptionPane.ERROR_MESSAGE);
        } else if (radO.isSelected() == false && radX.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "Selecione qual simbolo o jogador 1 utilizará!", "Atenção", JOptionPane.ERROR_MESSAGE);
        } else {
            if (txf_NomeJ1.getText().isEmpty()) {
                Variaveis.nJ1 = "Jogador 1";
            } else {
                Variaveis.nJ1 = txf_NomeJ1.getText();
            }
            if (txf_NomeJ2.getText().isEmpty()) {
                Variaveis.nJ2 = "Jogador 2";
            } else {
                Variaveis.nJ2 = txf_NomeJ2.getText();
            }
            if (radX.isSelected()) {
                Variaveis.simboloJ1 = "X";
                Variaveis.simboloJ2 = "O";
            } else if (radO.isSelected()) {
                Variaveis.simboloJ1 = "O";
                Variaveis.simboloJ2 = "X";
            }
            Variaveis.rodadas = Integer.parseInt(cbx_rodadas.getSelectedItem().toString());
            telaJogo jpJogo = new telaJogo();
            this.dispose();
            jpJogo.setVisible(true);

        }
    }//GEN-LAST:event_btn_OKActionPerformed

    private void txf_NomeJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_NomeJ2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_NomeJ2ActionPerformed

    private void txf_NomeJ1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_NomeJ1KeyTyped
        if (txf_NomeJ1.getText().length() >= limite) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite máximo de " + limite + " caractéres!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txf_NomeJ1KeyTyped

    private void txf_NomeJ2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txf_NomeJ2KeyTyped
        if (txf_NomeJ2.getText().length() >= limite) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limite máximo de " + limite + " caractéres!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txf_NomeJ2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaConfiguracao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaConfiguracao().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup XouO;
    private javax.swing.JButton btn_OK;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JComboBox<String> cbx_rodadas;
    private javax.swing.JLabel dica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radO;
    private javax.swing.JRadioButton radX;
    private javax.swing.JTextField txf_NomeJ1;
    private javax.swing.JTextField txf_NomeJ2;
    // End of variables declaration//GEN-END:variables

}
